sonar.projectKey=dataint-dcm-app
sonar.language=py

# defaults to project key
sonar.projectName=DCM Databricks Pipeline

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=pipelines

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Python version for analysis
sonar.python.version=3.12

# Coverage and test result files
sonar.python.coverage.reportPaths=coverage.xml

# Test sources
sonar.tests=tests

# Exclude these files from coverage analysis
sonar.coverage.exclusions=tests/**,.github/**