name: 'Security'
description: 'Runs SonarQube and Semgrep security scans'

inputs:
  SONARQUBE_SCAN_TOKEN:
    description: 'SonarQube scan token'
    required: true
  SONAR_URL:
    description: 'SonarQube host URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: 🌱 Checkout
      uses: actions/checkout@v4

    - name: 📥 Download report coverage.xml
      uses: actions/download-artifact@v4
      with:
        name: coverage-${{ github.sha }}
        path: packages/dcm-databricks-pipeline

    - name: 🩺 SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4
      with:
        projectBaseDir: packages/dcm-databricks-pipeline
      env:
        SONAR_TOKEN: ${{ inputs.SONARQUBE_SCAN_TOKEN }}
        SONAR_HOST_URL: ${{ inputs.SONAR_URL }}

    # To enable where the quality gate check is performed, uncomment the following step
    # - name: ✔️ SonarQube Quality Gate check
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   timeout-minutes: 10
    #   env:
    #     SONAR_TOKEN: ${{ inputs.SONARQUBE_SCAN_TOKEN }}

    # Skip any PR created by dependabot to avoid permission issues
    # And only for branches except main
    - name: 🔎 Run Semgrep scan
      if: (github.actor != 'dependabot[bot]' && github.ref != 'refs/heads/main')
      shell: bash
      run: |
        python -m pip install --quiet semgrep
        semgrep ci \
          --exclude-rule python.requests.security.disabled-cert-validation.disabled-cert-validation \
          --exclude-rule yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag \
          --exclude-rule yaml.github-actions.security.audit.unsafe-add-mask-workflow-command.unsafe-add-mask-workflow-command \
          --exclude-rule python.lang.security.audit.logging.logger-credential-leak.python-logger-credential-disclosure \
          --exclude-rule python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
      env:
        # Select rules for your scan with one of these two options.
        # Option 1: set hard-coded rulesets
        SEMGREP_RULES: >- # more at semgrep.dev/r
          p/security-audit
          p/secrets
          p/python
          p/github-actions
