#!/usr/bin/env python3
"""Generate .specify/extensions.yml from the `hooks:` block of extension.yml.

    wire_hooks.py <extension.yml> <.specify/extensions.yml>

extensions.yml tells spec-kit which command runs on which hook. Generated, not
hand-edited: as a manual step it kept the command names of whichever version first
installed it, and auto_execute_hooks fired hooks at names that no longer resolved.
One list of names, one source — extension.yml.

Stdlib only (no yq, no PyYAML): the reader below covers what a hooks: block needs,
it is not a YAML parser.
"""
import re
import shutil
import sys
from pathlib import Path

EXT_ID = "dcm"
# Ids this extension used to install under. Left in a file generated by an older
# version, they read as a third-party extension declaring the same hooks and main()
# would refuse to rewrite it — so they are pruned on both sides.
LEGACY_EXT_IDS = {"dcm-workflow"}
HEADER = """\
# Generated by spec-kit-dcm-workflow/scripts/sync-dcm-extension.sh — do not edit.
# Hook wiring comes from extension.yml (hooks:) so the command names here can
# never drift from provides.commands. Re-run the script after a pull."""


def say(msg):
    print("    → %s" % msg)


def warn(msg):
    print("    ✗ %s" % msg, file=sys.stderr)


def note(msg):
    print("      %s" % msg, file=sys.stderr)


def scalar(value):
    """`"a b"  # note` → `a b`."""
    value = value.strip()
    if value[:1] in ("'", '"'):
        end = value.find(value[0], 1)
        return value[1:end] if end != -1 else value[1:]
    return re.sub(r"\s+#.*$", "", value).strip()


def block(lines, key):
    """Lines indented under a top-level `key:` — comments and blanks kept."""
    out, inside = [], False
    for line in lines:
        if not inside:
            inside = re.match(r"^%s:\s*(#.*)?$" % re.escape(key), line) is not None
        elif line.strip() and not line[:1].isspace():
            break
        else:
            out.append(line)
    return out


def parse_hooks(lines):
    """[(event, [{field: value}, …]), …] — events with no entry are dropped."""
    events, entries, entry = [], None, None
    for line in block(lines, "hooks"):
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        event = re.match(r"^  (\w+):\s*(#.*)?$", line)
        if event:
            entries, entry = [], None
            events.append((event.group(1), entries))
            continue
        if entries is None:
            continue
        if text.startswith("-"):
            entry = {}
            entries.append(entry)
            text = text[1:].strip()
        field = re.match(r"^(\w+):\s*(.*)$", text) if entry is not None else None
        if field:
            entry[field.group(1)] = scalar(field.group(2))
    return [(event, items) for event, items in events if items]


def read_installed(path):
    """(extension ids, raw `settings:` lines, other extensions declaring hooks)."""
    if not path.exists():
        return [], [], set()
    lines = path.read_text(encoding="utf-8").splitlines()
    installed = [scalar(m.group(1)) for m in
                 (re.match(r"^\s*-\s*(.+)$", l) for l in block(lines, "installed")) if m]
    settings = [l for l in block(lines, "settings") if l.strip()]
    foreign = {scalar(m.group(1))
               for m in (re.match(r"^-?\s*extension:\s*(.+)$", l.strip())
                         for l in block(lines, "hooks")) if m}
    installed = [name for name in installed if name not in LEGACY_EXT_IDS]
    return installed, settings, foreign - {EXT_ID} - LEGACY_EXT_IDS


def quote(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def render(events, installed, settings):
    out = [HEADER, "installed:"]
    out += ["- %s" % name for name in installed]
    out.append("settings:")
    out += settings
    out.append("hooks:")
    for event, entries in events:
        out.append("  %s:" % event)
        for e in entries:
            command = e.get("command", "")
            out.append("  - extension: %s" % quote(e.get("extension", EXT_ID)))
            out.append("    command: %s" % quote(command))
            out.append("    enabled: %s" % ("false" if e.get("enabled") == "false" else "true"))
            out.append("    optional: %s" % ("true" if e.get("optional") == "true" else "false"))
            out.append("    priority: %s" % e.get("priority", "10"))
            out.append("    prompt: %s" % quote(e.get("prompt") or "Execute %s?" % command))
            if e.get("description"):
                out.append("    description: %s" % quote(e["description"]))
            out.append("    condition: null")
    return "\n".join(out) + "\n"


def main(src, dest):
    events = parse_hooks(src.read_text(encoding="utf-8").splitlines())
    if not events:
        warn("no hooks: block in extension.yml — extensions.yml left alone")
        return 0

    installed, settings, foreign = read_installed(dest)

    # Another extension declares hooks here: a wholesale rewrite would drop them.
    if foreign:
        warn("extensions.yml also declares hooks for: %s" % ", ".join(sorted(foreign)))
        note("Not rewriting it. Align the %s entries by hand with these names:" % EXT_ID)
        for event, entries in events:
            for e in entries:
                note("  %s → %s" % (event, e.get("command", "?")))
        return 0

    if EXT_ID not in installed:
        installed.append(EXT_ID)
    new = render(events, installed, settings or ["  auto_execute_hooks: true"])
    old = dest.read_text(encoding="utf-8") if dest.exists() else ""

    if old == new:
        say("extensions.yml already matches extension.yml")
        return 0

    dest.parent.mkdir(parents=True, exist_ok=True)
    if old:
        shutil.copyfile(dest, dest.with_suffix(".yml.bak"))
        stale = sorted(set(re.findall(r"command:\s*[\"']?([\w.\-]+)", old))
                       - {e.get("command", "") for _, items in events for e in items})
        if stale:
            say("rewired %d stale hook command name(s): %s" % (len(stale), ", ".join(stale)))
        say("extensions.yml updated (previous kept as extensions.yml.bak)")
    else:
        say("extensions.yml created")
    dest.write_text(new, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(Path(sys.argv[1]), Path(sys.argv[2])))
