"""Route modules re-exported for convenient import in ``app.main``."""

from __future__ import annotations

from . import (
    activities,
    admin_alert_rules,
    admin_audit,
    admin_bundle,
    admin_channels,
    admin_collectors,
    admin_embedded_dashboards,
    admin_kpi_config,
    admin_lz,
    admin_maintenance,
    admin_retention,
    admin_users,
    auth,
    chat,
    clusters,
    compute_metrics,
    costs,
    dashboard,
    datafactory,
    databricks,
    data_product_usage,
    databases,
    governance,
    health,
    monitoring_reports,
    notification_preferences,
    pipelines,
    security,
    sqs_to_raw_in,
    uc_usage,
    unity_catalog,
    users,
)

__all__ = [
    "admin_alert_rules",
    "admin_audit",
    "admin_bundle",
    "admin_channels",
    "admin_collectors",
    "admin_embedded_dashboards",
    "admin_kpi_config",
    "admin_lz",
    "admin_maintenance",
    "admin_retention",
    "admin_users",
    "activities",
    "auth",
    "chat",
    "clusters",
    "compute_metrics",
    "costs",
    "dashboard",
    "datafactory",
    "databricks",
    "data_product_usage",
    "databases",
    "governance",
    "health",
    "monitoring_reports",
    "notification_preferences",
    "pipelines",
    "security",
    "uc_usage",
    "unity_catalog",
    "users",
    "sqs_to_raw_in",
]
