name: "Continuous AI : Interact with private Claude"

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

permissions:
    id-token: write
    contents: write
    pull-requests: write
    issues: write
    actions: read

jobs:
  interact-with-claude-code:
    if: |
      (
        (github.event_name != 'pull_request' && (github.event.issue.pull_request || github.event.pull_request) && 
        (
          (github.event.comment && contains(github.event.comment.body, '@claude') && !contains(github.event.comment.body, '`@claude`') && github.event.comment.body != '@claude') ||
          (github.event.review && contains(github.event.review.body, '@claude') && !contains(github.event.review.body, '`@claude`') && github.event.review.body != '@claude')
        )
        ) ||
        (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude') && !contains(github.event.pull_request.body, '`@claude`') && github.event.pull_request.body != '@claude') ||
        (github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.body, '@claude') && !contains(github.event.issue.body, '`@claude`')) ||
        (
          github.event_name == 'issue_comment' 
          && !github.event.issue.pull_request 
          && (
              contains(github.event.comment.body, '@claude') 
              && !contains(github.event.comment.body, '`@claude`')
          )
          && github.event.sender.login != 'dp-cicd-continuous-ai-claude-code[bot]'
        )
      )
    runs-on: ubuntu-latest
    environment: continuous-ai
    steps:
      -
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - 
        name: Run claude code
        uses: TotalEnergiesCode/cicd-shared-workflows-continuous-ai/claude-code-interactive@8e21fd1b3291524a37b4fbf396531bdc258f5cc6 #v2.3.0
        with:
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          pr_number: ${{ github.event.pull_request.number || github.event.issue.number || '' }}
          oidc_api_key: ${{ vars.CICD_GH_OIDC_API_KEY }}
